table dim_country
	lineageTag: a8000001-0001-0001-0001-000000000001

	column country_key
		dataType: int64
		formatString: 0
		displayFolder: Keys
		lineageTag: a8000001-0001-0001-0001-000000000002
		summarizeBy: none
		sourceColumn: country_key

		annotation SummarizationSetBy = Automatic

	column 'Country Code'
		dataType: string
		lineageTag: a8000001-0001-0001-0001-000000000003
		summarizeBy: none
		sourceColumn: Country Code

		annotation SummarizationSetBy = Automatic

	partition dim_country = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\jackr\Downloads\my_spotify_data\star_schema\dim_country.csv"),[Delimiter=",", Columns=2, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"country_key", Int64.Type}, {"country_code", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"country_code", "Country Code"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

