table dim_album
	lineageTag: a4000001-0001-0001-0001-000000000001

	column album_key
		dataType: int64
		formatString: 0
		displayFolder: Keys
		lineageTag: a4000001-0001-0001-0001-000000000002
		summarizeBy: none
		sourceColumn: album_key

		annotation SummarizationSetBy = Automatic

	column 'Album Name'
		dataType: string
		lineageTag: a4000001-0001-0001-0001-000000000003
		summarizeBy: none
		sourceColumn: Album Name

		annotation SummarizationSetBy = Automatic

	partition dim_album = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\jackr\Downloads\my_spotify_data\star_schema\dim_album.csv"),[Delimiter=",", Columns=3, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"album_key", Int64.Type}, {"album_name", type text}, {"artist_key", Int64.Type}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"artist_key"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"album_name", "Album Name"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

