table fact_stream
	lineageTag: a1000001-0001-0001-0001-000000000001

	column stream_key
		dataType: int64
		formatString: 0
		displayFolder: Keys
		lineageTag: a1000001-0001-0001-0001-000000000002
		summarizeBy: none
		sourceColumn: stream_key

		annotation SummarizationSetBy = Automatic

	column ts_utc
		dataType: dateTime
		formatString: General Date
		lineageTag: a1000001-0001-0001-0001-000000000003
		summarizeBy: none
		sourceColumn: ts_utc

		annotation SummarizationSetBy = Automatic

	column stream_date_sk
		dataType: int64
		formatString: 0
		displayFolder: Keys
		lineageTag: a1000001-0001-0001-0001-000000000004
		summarizeBy: none
		sourceColumn: stream_date_sk

		annotation SummarizationSetBy = Automatic

	column hour
		dataType: int64
		formatString: 0
		lineageTag: a1000001-0001-0001-0001-000000000005
		summarizeBy: none
		sourceColumn: hour

		annotation SummarizationSetBy = Automatic

	column content_type_key
		dataType: int64
		formatString: 0
		displayFolder: Keys
		lineageTag: a1000001-0001-0001-0001-000000000006
		summarizeBy: none
		sourceColumn: content_type_key

		annotation SummarizationSetBy = Automatic

	column track_key
		dataType: int64
		formatString: 0
		displayFolder: Keys
		lineageTag: a1000001-0001-0001-0001-000000000007
		summarizeBy: none
		sourceColumn: track_key

		annotation SummarizationSetBy = Automatic

	column artist_key
		dataType: int64
		formatString: 0
		displayFolder: Keys
		lineageTag: a1000001-0001-0001-0001-000000000008
		summarizeBy: none
		sourceColumn: artist_key

		annotation SummarizationSetBy = Automatic

	column album_key
		dataType: int64
		formatString: 0
		displayFolder: Keys
		lineageTag: a1000001-0001-0001-0001-000000000009
		summarizeBy: none
		sourceColumn: album_key

		annotation SummarizationSetBy = Automatic

	column episode_key
		dataType: int64
		formatString: 0
		displayFolder: Keys
		lineageTag: a1000001-0001-0001-0001-000000000010
		summarizeBy: none
		sourceColumn: episode_key

		annotation SummarizationSetBy = Automatic

	column show_key
		dataType: int64
		formatString: 0
		displayFolder: Keys
		lineageTag: a1000001-0001-0001-0001-000000000011
		summarizeBy: none
		sourceColumn: show_key

		annotation SummarizationSetBy = Automatic

	column platform_key
		dataType: int64
		formatString: 0
		displayFolder: Keys
		lineageTag: a1000001-0001-0001-0001-000000000012
		summarizeBy: none
		sourceColumn: platform_key

		annotation SummarizationSetBy = Automatic

	column country_key
		dataType: int64
		formatString: 0
		displayFolder: Keys
		lineageTag: a1000001-0001-0001-0001-000000000013
		summarizeBy: none
		sourceColumn: country_key

		annotation SummarizationSetBy = Automatic

	column reason_start_key
		dataType: int64
		formatString: 0
		displayFolder: Keys
		lineageTag: a1000001-0001-0001-0001-000000000014
		summarizeBy: none
		sourceColumn: reason_start_key

		annotation SummarizationSetBy = Automatic

	column reason_end_key
		dataType: int64
		formatString: 0
		displayFolder: Keys
		lineageTag: a1000001-0001-0001-0001-000000000015
		summarizeBy: none
		sourceColumn: reason_end_key

		annotation SummarizationSetBy = Automatic

	column ms_played
		dataType: int64
		formatString: 0
		lineageTag: a1000001-0001-0001-0001-000000000016
		summarizeBy: sum
		sourceColumn: ms_played

		annotation SummarizationSetBy = Automatic

	column shuffle
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: a1000001-0001-0001-0001-000000000017
		summarizeBy: none
		sourceColumn: shuffle

		annotation SummarizationSetBy = Automatic

	column skipped
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: a1000001-0001-0001-0001-000000000018
		summarizeBy: none
		sourceColumn: skipped

		annotation SummarizationSetBy = Automatic

	column offline
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: a1000001-0001-0001-0001-000000000019
		summarizeBy: none
		sourceColumn: offline

		annotation SummarizationSetBy = Automatic

	column incognito_mode
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: a1000001-0001-0001-0001-000000000020
		summarizeBy: none
		sourceColumn: incognito_mode

		annotation SummarizationSetBy = Automatic

	partition fact_stream = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\jackr\Downloads\my_spotify_data\star_schema\fact_stream.csv"),[Delimiter=",", Columns=19, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"stream_key", Int64.Type}, {"ts_utc", type text}, {"date_key", Int64.Type}, {"hour", Int64.Type}, {"content_type_key", Int64.Type}, {"track_key", Int64.Type}, {"artist_key", Int64.Type}, {"album_key", Int64.Type}, {"episode_key", Int64.Type}, {"show_key", Int64.Type}, {"platform_key", Int64.Type}, {"country_key", Int64.Type}, {"reason_start_key", Int64.Type}, {"reason_end_key", Int64.Type}, {"ms_played", Int64.Type}, {"shuffle", type logical}, {"skipped", type logical}, {"offline", type logical}, {"incognito_mode", type logical}}),
				    #"Parsed DateTime" = Table.TransformColumns(#"Changed Type", {{"ts_utc", each DateTime.From(Text.BeforeDelimiter(_, "Z")), type datetime}}),
				    #"Added stream_date_sk" = Table.AddColumn(#"Parsed DateTime", "stream_date_sk", each Date.Year([ts_utc]) * 10000 + Date.Month([ts_utc]) * 100 + Date.Day([ts_utc]), Int64.Type),
				    #"Removed date_key" = Table.RemoveColumns(#"Added stream_date_sk", {"date_key"})
				in
				    #"Removed date_key"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

