table dim_show
	lineageTag: a6000001-0001-0001-0001-000000000001

	column show_key
		dataType: int64
		formatString: 0
		displayFolder: Keys
		lineageTag: a6000001-0001-0001-0001-000000000002
		summarizeBy: none
		sourceColumn: show_key

		annotation SummarizationSetBy = Automatic

	column 'Show Name'
		dataType: string
		lineageTag: a6000001-0001-0001-0001-000000000003
		summarizeBy: none
		sourceColumn: Show Name

		annotation SummarizationSetBy = Automatic

	partition dim_show = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\jackr\Downloads\my_spotify_data\star_schema\dim_show.csv"),[Delimiter=",", Columns=2, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"show_key", Int64.Type}, {"show_name", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"show_name", "Show Name"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

